on:
  push
jobs:
 list-pr:
  runs-on: ubuntu-18.04
  steps:
    -  name: List  Pull Request
       run: |
         curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/rililinx/test_gha/pulls
          

